-- MySQL Script generated by MySQL Workbench
-- Mon May 20 16:56:43 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_estaciona_facil
-- -----------------------------------------------------
DROP DATABASE `db_estaciona_facil`;
-- -----------------------------------------------------
-- Schema db_estaciona_facil
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_estaciona_facil` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_estaciona_facil` ;

-- -----------------------------------------------------
-- Table `db_estaciona_facil`.`tbl_endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_estaciona_facil`.`tbl_endereco` (
  `cod_endereco` INT(11) NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(55) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `bairro` VARCHAR(60) NOT NULL,
  `cod_cidade` INT(11) NOT NULL,
  PRIMARY KEY (`cod_endereco`),
  `cidade`VARCHAR(100) NOT NULL,
  `estado` VARCHAR(100) NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_estaciona_facil`.`tbl_fabricante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_estaciona_facil`.`tbl_fabricante` (
  `cod_fabricante` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`cod_fabricante`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_estaciona_facil`.`tbl_mensalista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_estaciona_facil`.`tbl_mensalista` (
  `cod_mensalista` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `cpf` VARCHAR(15) NOT NULL,
  `cod_telefone` INT(11) NOT NULL,
  `cod_endereco` INT(11) NOT NULL,
  PRIMARY KEY (`cod_mensalista`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_estaciona_facil`.`tbl_mensalista_endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_estaciona_facil`.`tbl_mensalista_endereco` (
  `cod_mensalista_endereco` INT(11) NOT NULL AUTO_INCREMENT,
  `cod_mensalista` INT(11) NOT NULL,
  `cod_endereco` INT(11) NOT NULL,
  PRIMARY KEY (`cod_mensalista_endereco`),
  INDEX `fk_mensalista_endereco` (`cod_endereco` ASC),
  INDEX `fk_endereco_mensalista` (`cod_mensalista` ASC),
  CONSTRAINT `fk_endereco_mensalista`
    FOREIGN KEY (`cod_mensalista`)
    REFERENCES `db_estaciona_facil`.`tbl_mensalista` (`cod_mensalista`),
  CONSTRAINT `fk_mensalista_endereco`
    FOREIGN KEY (`cod_endereco`)
    REFERENCES `db_estaciona_facil`.`tbl_endereco` (`cod_endereco`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_estaciona_facil`.`tbl_telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_estaciona_facil`.`tbl_telefone` (
  `cod_telefone` INT(11) NOT NULL AUTO_INCREMENT,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`cod_telefone`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_estaciona_facil`.`tbl_mensalista_telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_estaciona_facil`.`tbl_mensalista_telefone` (
  `cod_mensalista_telefone` INT(11) NOT NULL AUTO_INCREMENT,
  `cod_mensalista` INT(11) NOT NULL,
  `cod_telefone` INT(11) NOT NULL,
  PRIMARY KEY (`cod_mensalista_telefone`),
  INDEX `fk_mensalista_telefone` (`cod_telefone` ASC),
  INDEX `fk_telefone_mensalista` (`cod_mensalista` ASC),
  CONSTRAINT `fk_mensalista_telefone`
    FOREIGN KEY (`cod_telefone`)
    REFERENCES `db_estaciona_facil`.`tbl_telefone` (`cod_telefone`),
  CONSTRAINT `fk_telefone_mensalista`
    FOREIGN KEY (`cod_mensalista`)
    REFERENCES `db_estaciona_facil`.`tbl_mensalista` (`cod_mensalista`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_estaciona_facil`.`tbl_movimentacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_estaciona_facil`.`tbl_movimentacao` (
  `cod_movimento` INT(11) NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(8) NOT NULL,
  `modelo_carro` VARCHAR(15) NOT NULL,
  `data_hora_entrada` DATETIME NOT NULL,
  `data_hora_saida` DATETIME NULL DEFAULT NULL,
  `tipo` VARCHAR(10) NULL DEFAULT NULL,
  `tempo_permanencia` INT(11) NOT NULL DEFAULT '0',
  `valor_pago` DECIMAL(5,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`cod_movimento`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_estaciona_facil`.`tbl_preco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_estaciona_facil`.`tbl_preco` (
  `cod_preco` INT(11) NOT NULL AUTO_INCREMENT,
  `valor_primeira_hora` DECIMAL(5,2) NOT NULL,
  `valor_demais_horas` DECIMAL(5,2) NOT NULL,
  `tempo_tolerancia` INT(11) NOT NULL,
  `data_fim` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`cod_preco`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_estaciona_facil`.`tbl_veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_estaciona_facil`.`tbl_veiculo` (
  `cod_veiculo` INT(11) NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(7) NOT NULL,
  `modelo_carro` VARCHAR(30) NOT NULL,
  `cod_fabricante` INT(11) NOT NULL,
  PRIMARY KEY (`cod_veiculo`),
  INDEX `fk_veiculo_fabricante` (`cod_fabricante` ASC),
  CONSTRAINT `fk_veiculo_fabricante`
    FOREIGN KEY (`cod_fabricante`)
    REFERENCES `db_estaciona_facil`.`tbl_fabricante` (`cod_fabricante`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
