-- MySQL Script generated by MySQL Workbench
-- Mon May 20 13:53:04 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_estaciona_facil
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_estaciona_facil
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_estaciona_facil` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_estaciona_facil` ;

-- -----------------------------------------------------
-- Table `db_estaciona_facil`.`tbl_fabricante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_estaciona_facil`.`tbl_fabricante` (
  `cod_fabricante` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`cod_fabricante`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_estaciona_facil`.`tbl_movimentacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_estaciona_facil`.`tbl_movimentacao` (
  `cod_movimento` INT(11) NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(8) NOT NULL,
  `modelo_carro` VARCHAR(15) NOT NULL,
  `data_hora_entrada` DATETIME NOT NULL,
  `data_hora_saida` DATETIME NULL DEFAULT NULL,
  `tipo` VARCHAR(10) NULL DEFAULT NULL,
  `tempo_permanencia` INT(11) NOT NULL DEFAULT '0',
  `valor_pago` DECIMAL(5,2) NOT NULL DEFAULT '0.00',
  PRIMARY KEY (`cod_movimento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_estaciona_facil`.`tbl_preco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_estaciona_facil`.`tbl_preco` (
  `cod_preco` INT(11) NOT NULL AUTO_INCREMENT,
  `valor_primeira_hora` DECIMAL(5,2) NOT NULL,
  `valor_demais_horas` DECIMAL(5,2) NOT NULL,
  `tempo_tolerancia` INT(11) NOT NULL,
  `data_fim` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`cod_preco`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_estaciona_facil`.`tbl_veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_estaciona_facil`.`tbl_veiculo` (
  `cod_veiculo` INT(11) NOT NULL AUTO_INCREMENT,
  `placa` VARCHAR(7) NOT NULL,
  `modelo_carro` VARCHAR(30) NOT NULL,
  `cod_fabricante` INT(11) NOT NULL,
  PRIMARY KEY (`cod_veiculo`),
  INDEX `fk_veiculo_fabricante` (`cod_fabricante` ASC),
  CONSTRAINT `fk_veiculo_fabricante`
    FOREIGN KEY (`cod_fabricante`)
    REFERENCES `db_estaciona_facil`.`tbl_fabricante` (`cod_fabricante`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
